version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build-demo:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Use latest Flowplayer canary
          command: yarn upgrade @flowplayer/player@next
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build demo
          command: yarn demo
      - run: 
          name: install-awscli
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Upload adhoc site
          command: .tasks/upload-adhoc.bash
workflows:
  build-edge:
    jobs:
      - build-demo:
          context:
            - aws-eu-west-1-player
            - aws-eu-west-1-player-s3
